/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() 
    {
    	System.out.println(" This is awsume ");
      //  Library classUnderTest = new Library();
    }
}
